blank_issues_enabled: false
contact_links:
- name: Open an issue on the upstream
  url: https://github.com/koekeishiya/yabai/issues/new
  about: If your issue is not specific to newest Monterey release(s) and/or M1, you should probably file here
- name: Upstream's Monterey Issue
  url: https://github.com/koekeishiya/yabai/issues/923
  about: Discussion about this fork prior to 2021-11-04 happened here
- name: Upstream's Apple Silicon Issue
  url: https://github.com/koekeishiya/yabai/issues/725
- name: The upstream's dev branch
  url: https://github.com/koekeishiya/yabai/tree/the-future
  about: This is where your time might be better spent targetting PRs
